In [1]:
import numpy as np 
import sympy as sp
from sympy import *
from sympy import symbols
import itertools
import pandas

In [2]:
#E1, E2 = symbols('E1 E2')
E = [1,2]
K = 0.5
P = 0.7
J = [[0.1,0.2], [0.3,0.4]]
n_sites = 2
n_qbits = 2
n = n_qbits+n_sites
paulix = np.array([[0,1],
                  [1,0]])
pauliy = np.array([[0,-1j],
                  [1j,0]])
basis_vector = np.array([[0,0,0,0], [0,0,0,1],
                         [0,0,1,0],[0,0,1,1],
                         [0,1,0,0],[0,1,0,1],
                         [0,1,1,0],[0,1,1,1],
                         [1,0,0,0],[1,0,0,1],
                         [1,0,1,0],[1,0,1,1],
                         [1,1,0,0],[1,1,0,1],
                         [1,1,1,0],[1,1,1,1]])
basis_vec_star = np.conj(basis_vector)
#print(basis_vector, type(basis_vector), len(basis_vector)[0])
H = np.zeros((2**n ,2**n))
#testing the function ham
for j in range(len(basis_vector)):
    #onsite energy
    if basis_vector[j][2] == 0 and basis_vector[j][3] == 0:
        H[j][j] = 0
    if basis_vector[j][2] == 0 and basis_vector[j][3] == 1:
        H[j][j] = E[1]
    if basis_vector[j][2] == 1 and basis_vector[j][3] == 0:
        H[j][j] = E[0]
    if basis_vector[j][2] == 1 and basis_vector[j][3] == 1:
        H[j][j] = E[0] + E[1]
     
    #coupling
#     for i in range(len(basis_vector)):
#         if basis_vector[i][0] == 0 and basis_vector[i][1] == 0:
#             if basis_vector[i][2] == 0 and basis_vector[i][3] == 1 and j!=i:
#                 H[j][i] = K
#             if basis_vector[i][2] == 1 and basis_vector[i][3] == 0 and j!=i:
#                 H[j][i] = K
#         if basis_vector[i][0] == 0 and basis_vector[i][1] == 1:
#             if basis_vector[i][2] == 0 and basis_vector[i][3] == 1 and j!=i:
#                 H[j][i] = K
#             if basis_vector[i][2] == 1 and basis_vector[i][3] == 0 and j!=i:
#                 H[j][i] = K
#         if basis_vector[i][0] == 1 and basis_vector[i][1] == 0:
#             if basis_vector[i][2] == 0 and basis_vector[i][3] == 1 and j!=i:
#                 H[j][i] = K
#             if basis_vector[i][2] == 1 and basis_vector[i][3] == 0 and j!=i:
#                 H[j][i] = K
#         if basis_vector[i][0] == 1 and basis_vector[i][1] == 1:
#             if basis_vector[i][2] == 0 and basis_vector[i][3] == 1 and j!=i:
#                 H[j][i] = K
#             if basis_vector[i][2] == 1 and basis_vector[i][3] == 0 and j!=i:
#                 H[j][i] = K
print(H)
#print(Matrix(np.transpose(H)).eigenvals())
Matrix(H).eigenvals()
#print((np.transpose(basis_vector[1]))
#print(np.transpose(basis_vector[7]))
#print(np.dot(paulix,np.transpose(basis_vector[7])))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]]


{0: 4, 2.00000000000000: 4, 1.00000000000000: 4, 3.00000000000000: 4}

In [84]:
#agger(basis_vector)
np.dot(basis_vec_star,basis_vector)
print(basis_vec_star.shape,basis_vector.shape)

ValueError: shapes (16,4) and (16,4) not aligned: 4 (dim 1) != 16 (dim 0)

In [85]:
# E is the vector of energies.
# K is the matrix of hopping amplitudes
for i, a in enumerate(basis_vectors):
    for j, b in enumerate(basis_vectors):
        # we need to determine H[i,j]
        # It has three kinds of contributions
        # first one is E_k when the kth position is excited in both
        excited_in_both = a.astype(bool)&b.astype(bool)
        H[i,j] += (E*excited_in_both).sum()
        # second kind is K[k,l] when there's any "transition" where a[k] was 1, b[k] is 0, but a[l] was 0 and b[k] is 1.
        # this can certainly be expressed as some numpy operation but it eludes my mind, so here's a dirty double Python loop for now:
        for k, l in itertools.product(range(n),repeat=2): # equivalent to 2 nested loops over range(n)
            if a[k] and not b[k] and not a[l] and b[l]:
                H[i,j] += K[k,l]
print(H)

ValueError: operands could not be broadcast together with shapes (2,) (4,) 

In [5]:
basis_vectors = np.array([list(x) for x in itertools.product(range(2), repeat=n)]) #repeats (0,1) 4 times in a list
print(basis_vectors)

[[0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]]


In [5]:
def ham(E,K,P,J):
    n_sites = 2
    n_qbits = 2
    n = n_qbits+n_sites
    
    H = np.zeros((2**n ,2**n))
    
    #onsite energies
    for j in range(len(basis_vector)):
        if basis_vector[j][2] == 0 and basis_vector[j][3] == 0:
            H[j][j] = 0
        if basis_vector[j][2] == 0 and basis_vector[j][3] == 1:
            H[j][j] = E[1]
        if basis_vector[j][2] == 1 and basis_vector[j][3] == 0:
            H[j][j] = E[0]
        if basis_vector[j][2] == 1 and basis_vector[j][3] == 1:
            H[j][j] = E[0] + E[1]
    
    #coupling terms
    for j in range(len(basis_vector)):
        for i in range(len(basis_vector)):
            if basis_vector[j][2] == 0 and basis_vector[j][3] == 1:
                H[j][i] = K
            if basis_vector[j][2] == 1 and basis_vector[j][3] == 0:
                H[j][i] = K
            else:
                H[j][i] = 0

In [58]:
N = np.array([[0,0],
             [0,1]])
new_vec = np.zeros(2*n)
print(N * basis_vector[0])

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [53]:
def N11(x):
    N = np.array([[0,0],
                 [0,1]])
    if x[0][2] == 0:
        return 0
    if x[0][2] == 1:
        
        return 

def a1dag(x):
    
    

In [ ]:
#summation 
for i in range(n_sites):
    E_sum[i] = E[i] * N11
    

In [ ]:
#need to normalise 

In [2]:
from sympy.physics.secondquant import FKet
Fket([1,2])

NameError: name 'Fket' is not defined

In [49]:
from sympy.physics.quantum.dagger import Dagger
from sympy.physics.quantum.state import Ket, Bra
from sympy.physics.quantum.operator import Operator

Dagger(Ket('psi'))
Dagger(Bra('phi'))
Ket('psi')
b = Bra('b')
k = Ket('k')
ip = b*k
ip.ket
b*k

<b|k>

In [25]:
Dagger(Operator('a'))

Dagger(a)

In [29]:
from sympy.physics.quantum import InnerProduct, OuterProduct
Dagger(InnerProduct(Bra('a'),Ket('b')))

<b|a>

In [34]:
Dagger(OuterProduct(Ket('a'), Bra('b')))

|a><b|

In [35]:
A = Operator('A')
B = Operator('B')
Dagger(A*B)
Dagger(A+B)

Dagger(A) + Dagger(B)

In [41]:
from sympy import Matrix, I 
m = Matrix([[1, 1j],
           [2, I]])
m
Dagger(m)

Matrix([
[     1,  2],
[-1.0*I, -I]])

In [42]:
v = Matrix([[0,0,0,0], [0,0,0,1],
                         [0,0,1,0],[0,0,1,1],
                         [0,1,0,0],[0,1,0,1],
                         [0,1,1,0],[0,1,1,1]])
v

Matrix([
[0, 0, 0, 0],
[0, 0, 0, 1],
[0, 0, 1, 0],
[0, 0, 1, 1],
[0, 1, 0, 0],
[0, 1, 0, 1],
[0, 1, 1, 0],
[0, 1, 1, 1]])

In [43]:
Dagger(v)

Matrix([
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 1, 1, 1],
[0, 0, 1, 1, 0, 0, 1, 1],
[0, 1, 0, 1, 0, 1, 0, 1]])

In [53]:
from sympy.physics.quantum import TensorProduct

m1 = Matrix([[1,2],[2,1]])
m2 = Dagger(Matrix([[2,3],[2,4]]))
m3 = Matrix([[2,3],[2,4]])
TensorProduct(m1,m2)


Matrix([
[2, 2, 4, 4],
[3, 4, 6, 8],
[4, 4, 2, 2],
[6, 8, 3, 4]])

In [54]:
TensorProduct(m1,m3)

Matrix([
[2, 3, 4, 6],
[2, 4, 4, 8],
[4, 6, 2, 3],
[4, 8, 2, 4]])

In [55]:
# basis_vector = np.array([[0,0,0,0], [0,0,0,1],
#                          [0,0,1,0],[0,0,1,1],
#                          [0,1,0,0],[0,1,0,1],
#                          [0,1,1,0],[0,1,1,1],
#                          [1,0,0,0],[1,0,0,1],
#                          [1,0,1,0],[1,0,1,1],
#                          [1,1,0,0],[1,1,0,1],
#                          [1,1,1,0],[1,1,1,1]])

vector_basis = Dagger(basis_vector)
vector_basis

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

In [57]:
InnerProduct(vector_basis,basis_vector)

TypeError: KetBase subclass expected, got: array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 1]])

In [7]:
#np full returns array of given shape and type with fill_value
# hopping amplitudes between sites. Generally an arbitrary-ish matrix I believe, for now constant
K = np.full(fill_value=sp.symbols("K"), shape=(n_sites, n_sites))
# vector representing "driving by a classical field" for each site, constant for simplicity
P = np.full(fill_value=sp.symbols("P"), shape=(n_sites,))
K

array([[K, K],
       [K, K]], dtype=object)

In [8]:
H_QN = sp.Matrix.zeros(2**n)
H_QN

Matrix([
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
a = np.array([[1, 2], [6, 4]])
#for index, x in enumerate(a):
    #print(index, x)

for i, a_full in enumerate(basis_vectors):
    a = a_full[n_qbits:] #all but the first two elements => [:n_qbits] all but last two elements perhaps -
    
    #print(a, "", basis_vectors[i])
    for j, b_full in enumerate(basis_vectors):
        b = b_full[n_qbits:] # only the site part
        if i==j:
            excited_in_both = (a.astype(bool) & b.astype(bool)).astype(int) #converts to boolean matrix
            #print(excited_in_both, i, j, " ", a)
        for k, l in itertools.product(range(n_sites), repeat=2):  # equivalent to 2 nested loops over range(n)
            print(k, l)
            if a[k] and not b[k] and not a[l] and b[l]:
                H_QN[i, j] += K[k, l]
                

0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1
1 0
1 1
0 0
0 1


In [28]:
# since we're doing symbolic math, use a sympy matrix
H_QN = sp.Matrix.zeros(2**n)
for i, a_full in enumerate(basis_vectors):
    a = a_full[n_qbits:] # only the site part
    for j, b_full in enumerate(basis_vectors):
        b = b_full[n_qbits:] # only the site part
        
        # we need to determine H_QN[i,j]
        # It has three kinds of contributions
        # first one is E_k when the kth position is excited in both, but only diagonally.
        if i==j:
            excited_in_both = (a.astype(bool) & b.astype(bool)).astype(int)
            H_QN[i, j] += (E * excited_in_both).sum()
        # second kind is K[k,l] when there's any "transition" where a[k] was 1, b[k] is 0, but a[l] was 0 and b[k] is 1.
        # this can certainly be expressed as some numpy operation but it eludes my mind, so here's a dirty double Python loop for now:
        for k, l in itertools.product(range(n_sites), repeat=2):  # equivalent to 2 nested loops over range(n)
            if a[k] and not b[k] and not a[l] and b[l]:
                H_QN[i, j] += K[k, l]
H_QN   

Matrix([
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 2, K, 0, 0, 0, K, 0, 0, 0, K, 0, 0, 0, K, 0],
[0, K, 1, 0, 0, K, 0, 0, 0, K, 0, 0, 0, K, 0, 0],
[0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, K, 0, 0, 2, K, 0, 0, 0, K, 0, 0, 0, K, 0],
[0, K, 0, 0, 0, K, 1, 0, 0, K, 0, 0, 0, K, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, K, 0, 0, 0, K, 0, 0, 2, K, 0, 0, 0, K, 0],
[0, K, 0, 0, 0, K, 0, 0, 0, K, 1, 0, 0, K, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, K, 0, 0, 0, K, 0, 0, 0, K, 0, 0, 2, K, 0],
[0, K, 0, 0, 0, K, 0, 0, 0, K, 0, 0, 0, K, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]])

In [17]:
H_QN

Matrix([
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 2, K, 0, 0, 0, K, 0, 0, 0, K, 0, 0, 0, K, 0],
[0, K, 1, 0, 0, K, 0, 0, 0, K, 0, 0, 0, K, 0, 0],
[0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, K, 0, 0, 2, K, 0, 0, 0, K, 0, 0, 0, K, 0],
[0, K, 0, 0, 0, K, 1, 0, 0, K, 0, 0, 0, K, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, K, 0, 0, 0, K, 0, 0, 2, K, 0, 0, 0, K, 0],
[0, K, 0, 0, 0, K, 0, 0, 0, K, 1, 0, 0, K, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, K, 0, 0, 0, K, 0, 0, 0, K, 0, 0, 2, K, 0],
[0, K, 0, 0, 0, K, 0, 0, 0, K, 0, 0, 0, K, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]])