In [38]:
%matplotlib inline 
#outputs figures one cell below when called
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display
import sympy as sp 
from sympy import *
from sympy.physics.quantum import TensorProduct
sp.init_printing()


# The Hamiltonian Matrix of a 1+1 system
A system, composed of two subsystems, the Quantum Network (QN) and the Computational Layer (CL), contains 1 reservoir qubits, coupled with eachother, interacting with 1 computational qubits, through quantum tunneling. The general Hamiltonian of the QN of $l$ sites, is given as:
$$
\begin{equation}
\hat{H}_{QN} = \sum_lE_l\hat{a}_l^\dagger\hat{a}_l + \sum_{ll'}K_{ll'}(\hat{a}_l^\dagger\hat{a}_{l'}+ \hat{a}_{l'}^\dagger\hat{a}_l) + \sum_l(P_l^*\hat{a}_l + P_l\hat{a}_l^\dagger)
%|\psi_{qb}\rangle $\eqref{eq:hqn}$
\label{eq:hqn} \tag{1}
\end{equation}
$$


Where $E$ is the onsite energies of the states of the QN qubits. The $K$ terms define the so called hopping terms, which translates the state at one site to the other. Finally, the classical field excitation, $P$, is induced into the QN, which simulates a quantum operation. From $\eqref{eq:hqn}$, we see $H_{QN}$ is hermitian.

For the CL subsystem, the general hermertian Hamiltonian, for the $k^{th}$ qubit acting on $l^{th}$ site, is represented as follows: 
$$
\begin{equation}
\hat{H}_{CL} = \sum_{kl}(J_{kl}^*\hat{\sigma}_k^+\hat{a}_l + J_{kl}\hat{a}_l^\dagger\hat{\sigma}_k^-) 
%|\psi_{qb}\rangle $\eqref{eq:hqn}$
\label{eq:hcn} \tag{2}
\end{equation}
$$

Where the $J$ terms indicate the computational qubits (represented by $k$) entanglement between the QN qubits (represented by $l$). The pauli matrices are given as follows: 

$$
\begin{equation}
\sigma_k^{\pm} = \frac{1}{2}(\sigma_k^x \mp i\sigma_k^y)\newline
\sigma_k^{\pm} = \frac{1}{2}\left(\left(\begin{array}{cc}
0 & 1\\
1 & 0
\end{array}\right) \mp i\left(\begin{array}{cc}
0 & -i\\
i & 0
\end{array}\right)\right)\newline
\end{equation}
$$
where
$$
\begin{equation}
\sigma_k^{-} = \left(\begin{array}{cc}
0 & 1\\
0 & 0
\end{array}\right)\newline
\&\newline
\sigma_k^{+} = \left(\begin{array}{cc}
0 & 0\\
1 & 0
\end{array}\right)
%|\psi_{qb}\rangle $\eqref{eq:hqn}$
\label{eq:pauli} \tag{3}
\end{equation}
$$


where, the basis is taken as:
$$
\begin{equation}
\newline
|g\rangle = \left(\begin{array}{cc}
1\\
0
\end{array}\right)
\&\
|e\rangle = \left(\begin{array}{cc}
0\\
1
\end{array}\right)
\label{eq:adag} \tag{4}
\end{equation}
$$

and the full wavefunction (total hamiltonian follows same property) of an N+N system is:
$$
\begin{equation}
\newline
|\psi\rangle = |Q_{c1}\rangle \otimes |Q_{c2}\rangle \otimes |Q_{c3}\rangle \otimes...|Q_{r1}\rangle \otimes |Q_{r2}\rangle \otimes |Q_{r3}\rangle \otimes ...|Q_{rN}\rangle 
\label{eq:wavefn} \tag{5}
\end{equation}
$$

The total Hamiltonian of our system is then:
$
\begin{equation}
\hat{H} = \sum_lE_l\hat{a}_l^\dagger\hat{a}_l + \sum_{ll'}K_{ll'}(\hat{a}_l^\dagger\hat{a}_{l'}+ \hat{a}_{l'}^\dagger\hat{a}_l) + \sum_l(P_l^*\hat{a}_l + P_l\hat{a}_l^\dagger) + \sum_{kl}(J_{kl}^*\sigma_k^{+}\hat{a}_l + J_{kl}\hat{a}_l^\dagger\sigma_k^{-})
\label{eq:h}
\end{equation}
$

In [43]:
#nomenculture like E01 ground energy of qubit 1 
E11,E01,P1, E_11, E_01, J11 = sp.symbols("E_{11} E_{01} P_{1} E_{11c} E_{01c} J_{11}")
I2 = sp.eye(2)
a_dag = sp.Matrix([[0,0],
                   [1,0]])
sigmap = sp.Matrix([[0,0],[1,0]])
sigmam = sigmap.T

In [44]:
#state of our reservior system 
qr1 = sp.Matrix([[E01,P1.conjugate()],
                 [P1,E11]])
qr1

⎡        _____ ⎤
⎢E_{01}  P_{1} ⎥
⎢              ⎥
⎣P_{1}   E_{11}⎦

In [45]:
#hamil of res, if more tensor of all
qrh = qr1

In [46]:
c1 = sp.Matrix([[E_01,0],[0,E_11]])
c1

⎡E_{01c}     0   ⎤
⎢                ⎥
⎣   0     E_{11c}⎦

In [47]:
#hamilt of comp sys
ch = c1

In [48]:
#hamil of total system is thus
Hh = TensorProduct(ch,I2) + TensorProduct(I2,qrh)
Hh

⎡                       _____                                          ⎤
⎢E_{01c} + E_{01}       P_{1}               0                 0        ⎥
⎢                                                                      ⎥
⎢     P_{1}        E_{01c} + E_{11}         0                 0        ⎥
⎢                                                                      ⎥
⎢                                                           _____      ⎥
⎢       0                 0          E_{01} + E_{11c}       P_{1}      ⎥
⎢                                                                      ⎥
⎣       0                 0               P_{1}        E_{11c} + E_{11}⎦

In [49]:
#can edit values here if need be
E01,E_11c, E_01c = (0,0,0)

ch = ch.subs({"E_{11c}":E_11c, "E_{01c}":E_01c})
qrh = qrh.subs({"E_{11}":E11,"E_{01}":E01,"P_{1}":P1})
ch,qrh

⎛        ⎡       _____ ⎤⎞
⎜⎡0  0⎤  ⎢  0    P_{1} ⎥⎟
⎜⎢    ⎥, ⎢             ⎥⎟
⎝⎣0  0⎦  ⎣P_{1}  E_{11}⎦⎠

In [50]:
#just rewritting hamil with zero potential+gnd state
H = TensorProduct(ch,I2) + TensorProduct(I2,qrh)
H

⎡       _____                ⎤
⎢  0    P_{1}     0      0   ⎥
⎢                            ⎥
⎢P_{1}  E_{11}    0      0   ⎥
⎢                            ⎥
⎢                      _____ ⎥
⎢  0      0       0    P_{1} ⎥
⎢                            ⎥
⎣  0      0     P_{1}  E_{11}⎦

In [51]:
#now to introduce coupling 
def MTP(A,B):
    return TensorProduct(A,B)

In [52]:
H = H + J11.conjugate()*(MTP(sigmap,a_dag.T)) + J11 * (MTP(sigmam, a_dag))
H

⎡       _____                 ⎤
⎢  0    P_{1}     0       0   ⎥
⎢                             ⎥
⎢P_{1}  E_{11}  J_{11}    0   ⎥
⎢                             ⎥
⎢       ______          _____ ⎥
⎢  0    J_{11}    0     P_{1} ⎥
⎢                             ⎥
⎣  0      0     P_{1}   E_{11}⎦

## TIME EVOLUTION OPERATOR

In [53]:
E11,E01,P1, E_11, E_01, J11 = sp.symbols("E_{11} E_{01} P_{1} E_{11c} E_{01c} J_{11}")
Hcopy = H
E11,P1,J11 = (1,60,2)
H1 = Hcopy.subs({"E_{11}":E11,"P_{1}":P1, "J_{11}":J11})
H1

⎡0   60  0   0 ⎤
⎢              ⎥
⎢60  1   2   0 ⎥
⎢              ⎥
⎢0   2   0   60⎥
⎢              ⎥
⎣0   0   60  1 ⎦

$$
\begin{equation}
U = \exp(\frac{-i\hat{H}\tau}{\hbar})
\label{exp} \tag{6}
\end{equation}
$$

In [54]:
#hbar=1
tauhbar = 0.005

In [55]:
H2 = -1j * H1 * tauhbar
H2

⎡  0      -0.3⋅ⅈ      0        0    ⎤
⎢                                   ⎥
⎢-0.3⋅ⅈ  -0.005⋅ⅈ  -0.01⋅ⅈ     0    ⎥
⎢                                   ⎥
⎢  0     -0.01⋅ⅈ      0      -0.3⋅ⅈ ⎥
⎢                                   ⎥
⎣  0        0      -0.3⋅ⅈ   -0.005⋅ⅈ⎦

In [56]:
Hnp = np.array(H2).astype(np.complex128)
Hnp

array([[0.+0.j   , 0.-0.3j  , 0.+0.j   , 0.+0.j   ],
       [0.-0.3j  , 0.-0.005j, 0.-0.01j , 0.+0.j   ],
       [0.+0.j   , 0.-0.01j , 0.+0.j   , 0.-0.3j  ],
       [0.+0.j   , 0.+0.j   , 0.-0.3j  , 0.-0.005j]])

In [37]:
# = sp.exp(Hcopy)
U = np.exp(Hnp)
#U.simplify()
U

array([[1.        +0.j        , 0.95533649-0.29552021j,
        1.        +0.j        , 1.        +0.j        ],
       [0.95533649-0.29552021j, 0.9999875 -0.00499998j,
        0.99995   -0.00999983j, 1.        +0.j        ],
       [1.        +0.j        , 0.99995   -0.00999983j,
        1.        +0.j        , 0.95533649-0.29552021j],
       [1.        +0.j        , 1.        +0.j        ,
        0.95533649-0.29552021j, 0.9999875 -0.00499998j]])

In [72]:
#eg state 00, 01, 10, 11
psi1 = np.array([[1],[0],[0],[0]])
psi2 = np.array([[0],[1],[0],[0]])
psi3 = np.array([[0],[0],[1],[0]])
psi4 = np.array([[0],[0],[0],[1]])
print("00:\n",psi1,"\n01:\n",psi2, "\n10:\n",psi3,"\n11:\n", psi4)

00:
 [[1]
 [0]
 [0]
 [0]] 
01:
 [[0]
 [1]
 [0]
 [0]] 
10:
 [[0]
 [0]
 [1]
 [0]] 
11:
 [[0]
 [0]
 [0]
 [1]]


In [97]:
A = np.array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])
B = np.array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])
np.einsum('ij,jk -> ik', A,B) #ie matrix multi
np.einsum('ii -> i', A) #extract diag
np.einsum('ij, ij -> ij', A, B) #hadamard product
np.einsum('ij, ij -> ij', A,A) #element wise square
np.einsum('ii -> ', A)#adds diag ie trace
np.einsum('ij ->ji', A)#transpose
np.einsum('ij, ji -> ij', A,B)

array([[ 11,  24,  39,  56],
       [ 21,  44,  69,  96],
       [ 31,  64,  99, 136],
       [ 41,  84, 129, 176]])

In [77]:
psif1 = 1/np.sqrt(2) * psi1
pho1 = psif1 * psif1.T
pho1

array([[0.5, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ]])

In [ ]:
#U_dagU = I
#TensorProduct(U.T, U)

In [70]:
U.norm()

In [75]:
#D = 1/U.norm() * U
#D

⎡                                                                             
⎢                                                                             
⎢─────────────────────────────────────────────────────────────────────────────
⎢                            0.610103816207489⋅ⅈ                         -0.59
⎢4.0 - 2.77555756156289e-17⋅ℯ                    + 2.77555756156289e-17⋅ℯ     
⎢                                                                             
⎢                                                                             
⎢                                                                             
⎢─────────────────────────────────────────────────────────────────────────────
⎢                            0.610103816207489⋅ⅈ                         -0.59
⎢4.0 - 2.77555756156289e-17⋅ℯ                    + 2.77555756156289e-17⋅ℯ     
⎢                                                                             
⎢                                                   

In [76]:
#U_dagU = I
#TensorProduct(D.T, D)

⎡                                                                             
⎢                                                                             
⎢                                                                             
⎢─────────────────────────────────────────────────────────────────────────────
⎢                                                                             
⎢⎛                            0.610103816207489⋅ⅈ                         -0.5
⎢⎝4.0 - 2.77555756156289e-17⋅ℯ                    + 2.77555756156289e-17⋅ℯ    
⎢                                                                             
⎢                                                                             
⎢                   ⎛                  -0.307551908103745⋅ⅈ                   
⎢                   ⎝0.24995689061259⋅ℯ                     - 0.24995689061259
⎢─────────────────────────────────────────────────────────────────────────────
⎢                                                   

In [95]:
#gnd state 
psi_initial = sp.Matrix([[1],[0]])

In [96]:
#N = 
psi_initial.norm()

In [97]:
# v = (1/N, 0/N)
d = 1/psi_initial.norm()* psi_initial.normalized()
d

⎡1⎤
⎢ ⎥
⎣0⎦

In [65]:
psi_initial.is_normalized

AttributeError: 'MutableDenseMatrix' object has no attribute 'is_normalized'

In [100]:
psi1 = U*psi_initial
psi1


ShapeError: Matrix size mismatch: (2, 1) * (4, 4).

In [ ]:
#evolving state
t = 2000/tauhbar #how many steps/iterations of psi, 10 in this case
for j in range(t):
    