In [1]:
conda install qutip

Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

Note: you may need to restart the kernel to use updated packages.



PackagesNotFoundError: The following packages are not available from current channels:

  - qutip

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.




In [2]:
pip install qutip

Note: you may need to restart the kernel to use updated packages.


In [3]:
import qutip.testing
qutip.testing.run()


QuTiP: Quantum Toolbox in Python
Copyright (c) QuTiP team 2011 and later.
Current admin team: Alexander Pitchford, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, Eric Giguère, Boxi Li, Jake Lishman, Simon Cross and Asier Galicia.
Board members: Daniel Burgarth, Robert Johansson, Anton F. Kockum, Franco Nori and Will Zeng.
Original developers: R. J. Johansson & P. D. Nation.
Previous lead developers: Chris Granade & A. Grimsmo.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      4.7.1
Numpy Version:      1.20.3
Scipy Version:      1.7.1
Cython Version:     0.29.24
Matplotlib Version: 3.4.3
Python Version:     3.9.7
Number of CPUs:     16
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
Installation path:  D:\User\Rojar\Documents\Anaconda\lib\site-packages\qutip
Please cite QuTiP in your publication.
For your convenience a bibtex reference can be easily genera

tests/test_bofin_solvers.py::TestHSolverDL::test_pure_dephasing_model[liouvillian-qobjevo-combined-no_bnd_cut_approx] PASSED [  3%]
tests/test_bofin_solvers.py::TestHSolverDL::test_pure_dephasing_model[liouvillian-listevo-combined-bnd_cut_approx] PASSED [  3%]
tests/test_bofin_solvers.py::TestHSolverDL::test_pure_dephasing_model[liouvillian-listevo-combined-no_bnd_cut_approx] PASSED [  3%]
tests/test_bofin_solvers.py::TestHSolverDL::test_pure_dephasing_model[liouvillian-qobj-uncombined-bnd_cut_approx] PASSED [  3%]
tests/test_bofin_solvers.py::TestHSolverDL::test_pure_dephasing_model[liouvillian-qobj-uncombined-no_bnd_cut_approx] PASSED [  3%]
tests/test_bofin_solvers.py::TestHSolverDL::test_hsolverdl_backwards_compatibility[bnd_cut_approx] PASSED        [  3%]
tests/test_bofin_solvers.py::TestHSolverDL::test_hsolverdl_backwards_compatibility[renorm] PASSED                [  3%]
tests/test_bofin_solvers.py::TestHSolverDL::test_integration_error PASSED                                   

tests/test_brtools.py::test_diag_liou_mult[14] PASSED                                                            [  8%]
tests/test_brtools.py::test_diag_liou_mult[15] PASSED                                                            [  8%]
tests/test_brtools.py::test_diag_liou_mult[16] PASSED                                                            [  8%]
tests/test_brtools.py::test_diag_liou_mult[17] PASSED                                                            [  8%]
tests/test_brtools.py::test_diag_liou_mult[18] PASSED                                                            [  8%]
tests/test_brtools.py::test_diag_liou_mult[19] PASSED                                                            [  8%]
tests/test_brtools.py::test_diag_liou_mult[20] PASSED                                                            [  8%]
tests/test_brtools.py::test_diag_liou_mult[21] PASSED                                                            [  8%]
tests/test_brtools.py::test_diag_liou_mu

tests/test_control_pulseoptim.py::TestOptimization::test_invalid_oper_dtype[Ising state-to-state-list] PASSED    [ 12%]
tests/test_control_pulseoptim.py::TestOptimization::test_invalid_oper_dtype[Lindbladian amplitude damping channel-csr_matrix] PASSED [ 12%]
tests/test_control_pulseoptim.py::TestOptimization::test_invalid_oper_dtype[Lindbladian amplitude damping channel-list] PASSED [ 12%]
tests/test_control_pulseoptim.py::TestOptimization::test_invalid_oper_dtype[Symplectic coupled oscillators-csr_matrix] PASSED [ 12%]
tests/test_control_pulseoptim.py::TestOptimization::test_invalid_oper_dtype[Symplectic coupled oscillators-list] PASSED [ 12%]
tests/test_control_pulseoptim.py::TestOptimization::test_object_oriented_approach_and_gradient[Hadamard gate-default propagation] PASSED [ 12%]
tests/test_control_pulseoptim.py::TestOptimization::test_object_oriented_approach_and_gradient[Hadamard gate-Qobj propagation] PASSED [ 12%]
tests/test_control_pulseoptim.py::TestOptimization::test_obje

tests/test_cy_structs.py::test_coo2csr_struct[rep(1)] PASSED                                                     [ 16%]
tests/test_cy_structs.py::test_coo2csr_struct[rep(2)] PASSED                                                     [ 16%]
tests/test_cy_structs.py::test_coo2csr_struct[rep(3)] PASSED                                                     [ 16%]
tests/test_cy_structs.py::test_coo2csr_struct[rep(4)] PASSED                                                     [ 16%]
tests/test_cy_structs.py::test_coo2csr_struct[rep(5)] PASSED                                                     [ 16%]
tests/test_cy_structs.py::test_coo2csr_struct[rep(6)] PASSED                                                     [ 16%]
tests/test_cy_structs.py::test_coo2csr_struct[rep(7)] PASSED                                                     [ 16%]
tests/test_cy_structs.py::test_coo2csr_struct[rep(8)] PASSED                                                     [ 16%]
tests/test_cy_structs.py::test_coo2csr_s

tests/test_device.py::test_analytical_evolution[DispersiveCavityQED-RY] PASSED                                   [ 20%]
tests/test_device.py::test_analytical_evolution[DispersiveCavityQED-ISWAP] PASSED                                [ 20%]
tests/test_device.py::test_analytical_evolution[DispersiveCavityQED-SQRTISWAP] SKIPPED (unconditional skip)      [ 20%]
tests/test_device.py::test_analytical_evolution[DispersiveCavityQED-CNOT] PASSED                                 [ 20%]
tests/test_device.py::test_analytical_evolution[LinearSpinChain-Z] PASSED                                        [ 20%]
tests/test_device.py::test_analytical_evolution[LinearSpinChain-X] PASSED                                        [ 20%]
tests/test_device.py::test_analytical_evolution[LinearSpinChain-Y] PASSED                                        [ 20%]
tests/test_device.py::test_analytical_evolution[LinearSpinChain-SNOT] PASSED                                     [ 20%]
tests/test_device.py::test_analytical_ev

tests/test_dimensions.py::TestSuperOperatorDimsModification::test_dims_to_tensor_perm[operator-bra] PASSED       [ 24%]
tests/test_dimensions.py::TestSuperOperatorDimsModification::test_dims_idxs_to_tensor_idxs[ket preserved] PASSED [ 24%]
tests/test_dimensions.py::TestSuperOperatorDimsModification::test_dims_idxs_to_tensor_idxs[tensor-ket preserved] PASSED [ 24%]
tests/test_dimensions.py::TestSuperOperatorDimsModification::test_dims_idxs_to_tensor_idxs[bra preserved] PASSED [ 24%]
tests/test_dimensions.py::TestSuperOperatorDimsModification::test_dims_idxs_to_tensor_idxs[tensor-bra preserved] PASSED [ 24%]
tests/test_dimensions.py::TestSuperOperatorDimsModification::test_dims_idxs_to_tensor_idxs[oper preserved] PASSED [ 24%]
tests/test_dimensions.py::TestSuperOperatorDimsModification::test_dims_idxs_to_tensor_idxs[tensor-oper preserved] PASSED [ 24%]
tests/test_dimensions.py::TestSuperOperatorDimsModification::test_dims_idxs_to_tensor_idxs[super-oper] PASSED    [ 24%]
tests/test_dimens

tests/test_enr_state_operator.py::TestOperator::test_space_size_reduction[tensor-equal-3-2] PASSED               [ 26%]
tests/test_enr_state_operator.py::TestOperator::test_space_size_reduction[tensor-equal-3-3] PASSED               [ 26%]
tests/test_enr_state_operator.py::TestOperator::test_space_size_reduction[tensor-equal-3-1000000] PASSED         [ 26%]
tests/test_enr_state_operator.py::TestOperator::test_space_size_reduction[tensor-equal-4-1] PASSED               [ 26%]
tests/test_enr_state_operator.py::TestOperator::test_space_size_reduction[tensor-equal-4-2] PASSED               [ 27%]
tests/test_enr_state_operator.py::TestOperator::test_space_size_reduction[tensor-equal-4-3] PASSED               [ 27%]
tests/test_enr_state_operator.py::TestOperator::test_space_size_reduction[tensor-equal-4-1000000] PASSED         [ 27%]
tests/test_enr_state_operator.py::TestOperator::test_space_size_reduction[tensor-not-equal-1] PASSED             [ 27%]
tests/test_enr_state_operator.py::TestOp

tests/test_entropy.py::TestLinearEntropy::test_pure_state[rep(8)] PASSED                                         [ 31%]
tests/test_entropy.py::TestLinearEntropy::test_pure_state[rep(9)] PASSED                                         [ 31%]
tests/test_entropy.py::TestLinearEntropy::test_pure_state[rep(10)] PASSED                                        [ 31%]
tests/test_entropy.py::TestConcurrence::test_maximally_entangled[bell00] PASSED                                  [ 31%]
tests/test_entropy.py::TestConcurrence::test_maximally_entangled[bell01] PASSED                                  [ 31%]
tests/test_entropy.py::TestConcurrence::test_maximally_entangled[bell10] PASSED                                  [ 31%]
tests/test_entropy.py::TestConcurrence::test_maximally_entangled[bell11] PASSED                                  [ 31%]
tests/test_entropy.py::TestConcurrence::test_nonzero[rep(1)] PASSED                                              [ 31%]
tests/test_entropy.py::TestConcurrence::

tests/test_expect.py::TestKnownExpectation::test_operator_by_basis[basis-ket6] PASSED                            [ 35%]
tests/test_expect.py::TestKnownExpectation::test_operator_by_basis[basis-ket7] PASSED                            [ 35%]
tests/test_expect.py::TestKnownExpectation::test_operator_by_basis[basis-ket8] PASSED                            [ 35%]
tests/test_expect.py::TestKnownExpectation::test_operator_by_basis[basis-ket9] PASSED                            [ 35%]
tests/test_expect.py::TestKnownExpectation::test_operator_by_basis[basis-dm0] PASSED                             [ 35%]
tests/test_expect.py::TestKnownExpectation::test_operator_by_basis[basis-dm1] PASSED                             [ 35%]
tests/test_expect.py::TestKnownExpectation::test_operator_by_basis[basis-dm2] PASSED                             [ 35%]
tests/test_expect.py::TestKnownExpectation::test_operator_by_basis[basis-dm3] PASSED                             [ 35%]
tests/test_expect.py::TestKnownExpectati

tests/test_floquet.py::TestFloquet::testFloquetMasterEquation2[100] PASSED                                       [ 39%]
tests/test_floquet.py::TestFloquet::testFloquetMasterEquation2[200] PASSED                                       [ 39%]
tests/test_floquet.py::TestFloquet::testFloquetRates PASSED                                                      [ 39%]
tests/test_gates.py::TestExplicitForm::test_swap PASSED                                                          [ 39%]
tests/test_gates.py::TestExplicitForm::test_toffoli[3-012] PASSED                                                [ 39%]
tests/test_gates.py::TestExplicitForm::test_toffoli[3-021] PASSED                                                [ 39%]
tests/test_gates.py::TestExplicitForm::test_toffoli[3-102] PASSED                                                [ 39%]
tests/test_gates.py::TestExplicitForm::test_toffoli[3-120] PASSED                                                [ 39%]
tests/test_gates.py::TestExplicitForm::t

tests/test_krylovsolve.py::TestKrylovSolve::test_06_check_e_ops_callable[intermediate dim-normal tlist] PASSED   [ 43%]
tests/test_krylovsolve.py::TestKrylovSolve::test_06_check_e_ops_callable[intermediate dim-single element tlist] PASSED [ 43%]
tests/test_krylovsolve.py::TestKrylovSolve::test_06_check_e_ops_callable[intermediate dim-empty tlist] PASSED    [ 43%]
tests/test_krylovsolve.py::TestKrylovSolve::test_06_check_e_ops_callable[large dim-normal tlist] PASSED          [ 43%]
tests/test_krylovsolve.py::TestKrylovSolve::test_06_check_e_ops_callable[large dim-single element tlist] PASSED  [ 44%]
tests/test_krylovsolve.py::TestKrylovSolve::test_06_check_e_ops_callable[large dim-empty tlist] PASSED           [ 44%]
tests/test_krylovsolve.py::TestKrylovSolve::test_07_check_e_ops_list_single_callable[small dim-normal tlist-[c]] PASSED [ 44%]
tests/test_krylovsolve.py::TestKrylovSolve::test_07_check_e_ops_list_single_callable[small dim-normal tlist-[q]] PASSED [ 44%]
tests/test_krylovsol

tests/test_measurement.py::test_measurement_statistics_povm[PY_ket] PASSED                                       [ 48%]
tests/test_measurement.py::test_measurement_statistics_povm[PY_dm] PASSED                                        [ 48%]
tests/test_measurement.py::test_measurement_statistics_ind[partial_ket] PASSED                                   [ 48%]
tests/test_measurement.py::test_measurement_statistics_ind[partial_dm] PASSED                                    [ 48%]
tests/test_measurement.py::test_measurement_statistics_povm_input_errors PASSED                                  [ 48%]
tests/test_measurement.py::test_measurement_statistics_observable_input_errors PASSED                            [ 48%]
tests/test_measurement.py::test_measure_observable[sigmaz_ket1] PASSED                                           [ 48%]
tests/test_measurement.py::test_measure_observable[sigmaz_ket2] PASSED                                           [ 48%]
tests/test_measurement.py::test_measure_

tests/test_metrics.py::Test_fidelity::test_orthogonal[5-pure-pure] PASSED                                        [ 52%]
tests/test_metrics.py::Test_fidelity::test_orthogonal[10-mixed-mixed] PASSED                                     [ 52%]
tests/test_metrics.py::Test_fidelity::test_orthogonal[10-mixed-pure] PASSED                                      [ 52%]
tests/test_metrics.py::Test_fidelity::test_orthogonal[10-pure-mixed] PASSED                                      [ 52%]
tests/test_metrics.py::Test_fidelity::test_orthogonal[10-pure-pure] PASSED                                       [ 52%]
tests/test_metrics.py::Test_fidelity::test_orthogonal[15-mixed-mixed] PASSED                                     [ 52%]
tests/test_metrics.py::Test_fidelity::test_orthogonal[15-mixed-pure] PASSED                                      [ 52%]
tests/test_metrics.py::Test_fidelity::test_orthogonal[15-pure-mixed] PASSED                                      [ 52%]
tests/test_metrics.py::Test_fidelity::te

tests/test_metrics.py::Test_hellinger_dist::test_state_with_itself[pure-5] PASSED                                [ 56%]
tests/test_metrics.py::Test_hellinger_dist::test_state_with_itself[pure-10] PASSED                               [ 56%]
tests/test_metrics.py::Test_hellinger_dist::test_state_with_itself[pure-15] PASSED                               [ 56%]
tests/test_metrics.py::Test_hellinger_dist::test_state_with_itself[pure-25] PASSED                               [ 56%]
tests/test_metrics.py::Test_hellinger_dist::test_state_with_itself[pure-100] PASSED                              [ 56%]
tests/test_metrics.py::Test_hellinger_dist::test_state_with_itself[mixed-2] PASSED                               [ 56%]
tests/test_metrics.py::Test_hellinger_dist::test_state_with_itself[mixed-5] PASSED                               [ 56%]
tests/test_metrics.py::Test_hellinger_dist::test_state_with_itself[mixed-10] PASSED                              [ 56%]
tests/test_metrics.py::Test_hellinger_di

tests/test_metrics.py::Test_dnorm::test_qubit_known_cases[dense-0.31-0.62-had_mixture] SKIPPED (Skipping dno...) [ 60%]
tests/test_metrics.py::Test_dnorm::test_qubit_known_cases[dense-0.001-0.002-swap_map] SKIPPED (Skipping dnor...) [ 60%]
tests/test_metrics.py::Test_dnorm::test_qubit_known_cases[dense-0.0031-0.006199997-swap_map] SKIPPED (Skippi...) [ 60%]
tests/test_metrics.py::Test_dnorm::test_qubit_known_cases[dense-0.01-0.01999992-swap_map] SKIPPED (Skipping ...) [ 60%]
tests/test_metrics.py::Test_dnorm::test_qubit_known_cases[dense-0.031-0.06199752-swap_map] SKIPPED (Skipping...) [ 60%]
tests/test_metrics.py::Test_dnorm::test_qubit_known_cases[dense-0.1-0.1999162-swap_map] SKIPPED (Skipping dn...) [ 60%]
tests/test_metrics.py::Test_dnorm::test_qubit_known_cases[dense-0.31-0.6173918-swap_map] SKIPPED (Skipping d...) [ 60%]
tests/test_metrics.py::Test_dnorm::test_qubit_scalar[2] SKIPPED (Skipping dnorm tests -- cvxpy and cvxopt ca...) [ 60%]
tests/test_metrics.py::Test_dnorm::test_

tests/test_piqs.py::TestDicke::test_collective_algebra PASSED                                                    [ 65%]
tests/test_piqs.py::TestDicke::test_block_matrix PASSED                                                          [ 65%]
tests/test_piqs.py::TestDicke::test_dicke_basis PASSED                                                           [ 65%]
tests/test_piqs.py::TestDicke::test_dicke PASSED                                                                 [ 65%]
tests/test_piqs.py::TestDicke::test_excited PASSED                                                               [ 65%]
tests/test_piqs.py::TestDicke::test_superradiant PASSED                                                          [ 65%]
tests/test_piqs.py::TestDicke::test_ghz PASSED                                                                   [ 65%]
tests/test_piqs.py::TestDicke::test_ground PASSED                                                                [ 65%]
tests/test_piqs.py::TestDicke::test_iden

tests/test_qobj.py::test_QobjGetItem PASSED                                                                      [ 69%]
tests/test_qobj.py::test_CheckMulType PASSED                                                                     [ 69%]
tests/test_qobj.py::test_Qobj_Spmv PASSED                                                                        [ 69%]
tests/test_qobj.py::test_QobjConjugate PASSED                                                                    [ 69%]
tests/test_qobj.py::test_QobjDagger PASSED                                                                       [ 69%]
tests/test_qobj.py::test_QobjDiagonals PASSED                                                                    [ 69%]
tests/test_qobj.py::test_QobjEigenEnergies PASSED                                                                [ 69%]
tests/test_qobj.py::test_QobjEigenStates PASSED                                                                  [ 69%]
tests/test_qobj.py::test_QobjExpm PASSED

tests/test_qubitcircuit.py::TestQubitCircuit::test_gate_product PASSED                                           [ 73%]
tests/test_qubitcircuit.py::TestQubitCircuit::test_wstate PASSED                                                 [ 73%]
tests/test_qubitcircuit.py::TestQubitCircuit::test_latex_code PASSED                                             [ 73%]
tests/test_qubitcircuit.py::TestQubitCircuit::test_latex_code_non_reversed PASSED                                [ 73%]
tests/test_qubits.py::TestQubits::testQubitStates PASSED                                                         [ 73%]
tests/test_random.py::test_rand_unitary[rand_unitary-rep(1)] PASSED                                              [ 73%]
tests/test_random.py::test_rand_unitary[rand_unitary-rep(2)] PASSED                                              [ 73%]
tests/test_random.py::test_rand_unitary[rand_unitary-rep(3)] PASSED                                              [ 73%]
tests/test_random.py::test_rand_unitary[

tests/test_sesolve.py::TestSESolve::test_01_1_state_with_const_H PASSED                                          [ 77%]
tests/test_sesolve.py::TestSESolve::test_01_1_unitary_with_const_H PASSED                                        [ 77%]
tests/test_sesolve.py::TestSESolve::test_02_1_state_with_func_H PASSED                                           [ 77%]
tests/test_sesolve.py::TestSESolve::test_02_2_unitary_with_func_H PASSED                                         [ 77%]
tests/test_sesolve.py::TestSESolve::test_03_1_state_with_list_func_H PASSED                                      [ 77%]
tests/test_sesolve.py::TestSESolve::test_03_2_unitary_with_list_func_H PASSED                                    [ 77%]
tests/test_sesolve.py::TestSESolve::test_04_1_state_with_list_str_H PASSED                                       [ 77%]
tests/test_sesolve.py::TestSESolve::test_04_2_unitary_with_list_func_H PASSED                                    [ 78%]
tests/test_sesolve.py::TestSESolve::test

tests/test_steadystate.py::test_qubit[iterative-bicgstab] PASSED                                                 [ 82%]
tests/test_steadystate.py::test_exact_solution_for_simple_methods[direct] PASSED                                 [ 82%]
tests/test_steadystate.py::test_exact_solution_for_simple_methods[direct_mkl] SKIPPED (MKL extensions not fo...) [ 82%]
tests/test_steadystate.py::test_exact_solution_for_simple_methods[direct_dense] PASSED                           [ 82%]
tests/test_steadystate.py::test_exact_solution_for_simple_methods[direct_rcm] PASSED                             [ 82%]
tests/test_steadystate.py::test_exact_solution_for_simple_methods[direct_wbm] PASSED                             [ 82%]
tests/test_steadystate.py::test_exact_solution_for_simple_methods[eigen] PASSED                                  [ 82%]
tests/test_steadystate.py::test_exact_solution_for_simple_methods[eigen_rcm] PASSED                              [ 82%]
tests/test_steadystate.py::test_exact_so

tests/test_superoper.py::TestSuper_td::test_lindblad_dissipator_td PASSED                                        [ 86%]
tests/test_td_formats.py::test_setTDFormatCheckMC PASSED                                                         [ 86%]
tests/test_tensor.py::test_tensor_contract_ident PASSED                                                          [ 86%]
tests/test_tensor.py::test_tensor_contract_other PASSED                                                          [ 86%]
tests/test_tensor.py::test_tensor_swap_other PASSED                                                              [ 86%]
tests/test_three_level.py::testThreeStates PASSED                                                                [ 86%]
tests/test_three_level.py::testThreeOps PASSED                                                                   [ 86%]
tests/test_transfertensor.py::test_ttmsolve_jc_model PASSED                                                      [ 86%]
tests/test_utilities.py::test_n_thermal[

tests/test_utilities.py::test_unit_conversions_loop[GHz-mK-GHz] PASSED                                           [ 90%]
tests/test_utilities.py::test_unit_conversions_loop[GHz-mK-mK] PASSED                                            [ 90%]
tests/test_utilities.py::test_unit_conversions_loop[mK-J-J] PASSED                                               [ 90%]
tests/test_utilities.py::test_unit_conversions_loop[mK-J-eV] PASSED                                              [ 90%]
tests/test_utilities.py::test_unit_conversions_loop[mK-J-meV] PASSED                                             [ 90%]
tests/test_utilities.py::test_unit_conversions_loop[mK-J-GHz] PASSED                                             [ 90%]
tests/test_utilities.py::test_unit_conversions_loop[mK-J-mK] PASSED                                              [ 90%]
tests/test_utilities.py::test_unit_conversions_loop[mK-eV-J] PASSED                                              [ 90%]
tests/test_utilities.py::test_unit_conve

tests/test_utilities.py::test_unit_clebsch_delta_m[7.5-5] PASSED                                                 [ 94%]
tests/test_utilities.py::test_unit_clebsch_delta_m[7.5-7.5] PASSED                                               [ 94%]
tests/test_utilities.py::test_unit_clebsch_delta_m[7.5-10] PASSED                                                [ 94%]
tests/test_utilities.py::test_unit_clebsch_delta_m[7.5-12.5] PASSED                                              [ 94%]
tests/test_utilities.py::test_unit_clebsch_delta_m[10-0.5] PASSED                                                [ 94%]
tests/test_utilities.py::test_unit_clebsch_delta_m[10-1.0] PASSED                                                [ 94%]
tests/test_utilities.py::test_unit_clebsch_delta_m[10-1.5] PASSED                                                [ 94%]
tests/test_utilities.py::test_unit_clebsch_delta_m[10-2.0] PASSED                                                [ 95%]
tests/test_utilities.py::test_unit_clebs

tests/test_wigner.py::test_spin_q_function[pure-spin-three] PASSED                                               [ 99%]
tests/test_wigner.py::test_spin_q_function[pure-spin-thirteen-half] PASSED                                       [ 99%]
tests/test_wigner.py::test_spin_q_function[pure-spin-seven] PASSED                                               [ 99%]
tests/test_wigner.py::test_spin_q_function[mixed-spin-one-half] PASSED                                           [ 99%]
tests/test_wigner.py::test_spin_q_function[mixed-spin-three] PASSED                                              [ 99%]
tests/test_wigner.py::test_spin_q_function[mixed-spin-thirteen-half] PASSED                                      [ 99%]
tests/test_wigner.py::test_spin_q_function[mixed-spin-seven] PASSED                                              [ 99%]
tests/test_wigner.py::test_spin_q_function_normalized[pure-spin-one-half] PASSED                                 [ 99%]
tests/test_wigner.py::test_spin_q_functi

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Image
from qutip import (Qobj, about, basis, coherent, coherent_dm, create, destroy,
                   expect, fock, fock_dm, mesolve, qeye, sigmax, sigmay,
                   sigmaz, tensor, thermal_dm)

%matplotlib inline

In [2]:
Image(filename='images/qobj.png')

FileNotFoundError: [Errno 2] No such file or directory: 'images/qobj.png'

In [5]:
q = Qobj([[1],[0]])
q

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [6]:
q.shape

(2, 1)

In [7]:
q.dims

[[2], [1]]

In [8]:
q.data

<2x1 sparse matrix of type '<class 'numpy.complex128'>'
	with 1 stored elements in Compressed Sparse Row format>

In [9]:
q.full()

array([[1.+0.j],
       [0.+0.j]])

In [10]:
q.isherm, q.type

(False, 'ket')

In [18]:
sy = Qobj([[0, -1j], [1j, 0]]) #sigma y pauli 
sy
#sy.isherm

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [13]:
sz = Qobj([[1,0],[0,-1]])
sz

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [15]:
H = 1.0 * sz + 0.1 * sy
print('qbit hamiltonian = \n')
H

qbit hamiltonian = 



Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.+0.j   0.-0.1j]
 [ 0.+0.1j -1.+0.j ]]

In [16]:
sy.dag() #herm conjugate

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [19]:
H.tr()

0.0

In [20]:
H.eigenenergies()

array([-1.00498756,  1.00498756])

In [21]:
help(Qobj)

Help on class Qobj in module qutip.qobj:

class Qobj(builtins.object)
 |  Qobj(inpt=None, dims=None, shape=None, type=None, isherm=None, copy=True, fast=False, superrep=None, isunitary=None)
 |  
 |  A class for representing quantum objects, such as quantum operators
 |  and states.
 |  
 |  The Qobj class is the QuTiP representation of quantum operators and state
 |  vectors. This class also implements math operations +,-,* between Qobj
 |  instances (and / by a C-number), as well as a collection of common
 |  operator/state operations.  The Qobj constructor optionally takes a
 |  dimension ``list`` and/or shape ``list`` as arguments.
 |  
 |  Parameters
 |  ----------
 |  inpt : array_like
 |      Data for vector/matrix representation of the quantum object.
 |  dims : list
 |      Dimensions of object used for tensor products.
 |  shape : list
 |      Shape of underlying data structure (matrix shape).
 |  copy : bool
 |      Flag specifying whether Qobj should get a copy of the
 |   

In [22]:
N = 2 # of staes in H
n = 1 # state occupied

basis(N,n) #equivilant to fock (N,n)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [24]:
fock(4,2)

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]]

In [ ]:
# a fock state as density matrix
fock_dm(5, 2)  # 5 = hilbert space size, 2 = state that is occupied
# coherent state as density matrix
coherent_dm(N=8, alpha=1.0)

In [25]:
sigmax()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

In [26]:
sigmay()


Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [27]:
sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [28]:
destroy(N=8) #annhil operator 8b8 H space

Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         1.41421356 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         1.73205081 0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         2.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         2.23606798
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  2.44948974 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         2.64575131]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]]

In [30]:
create(N=8)

Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [1.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         1.41421356 0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         1.73205081 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         2.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         2.23606798 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         2.44948974
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  2.64575131 0.        ]]

In [32]:
destroy(8).dag()

Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [1.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         1.41421356 0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         1.73205081 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         2.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         2.23606798 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         2.44948974
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  2.64575131 0.        ]]

In [33]:
def comm(o1,o2):
    return o1*o2 - o2*o1

a = destroy(5)

comm(a, a.dag())

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. -4.]]

In [37]:
sz1 = tensor(sigmaz(), qeye(2))
sz1

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]

In [38]:
help(basis)

Help on function basis in module qutip.states:

basis(dimensions, n=None, offset=None)
    Generates the vector representation of a Fock state.
    
    Parameters
    ----------
    dimensions : int or list of ints
        Number of Fock states in Hilbert space.  If a list, then the resultant
        object will be a tensor product over spaces with those dimensions.
    
    n : int or list of ints, optional (default 0 for all dimensions)
        Integer corresponding to desired number state, defaults to 0 for all
        dimensions if omitted.  The shape must match ``dimensions``, e.g. if
        ``dimensions`` is a list, then ``n`` must either be omitted or a list
        of equal length.
    
    offset : int or list of ints, optional (default 0 for all dimensions)
        The lowest number state that is included in the finite number state
        representation of the state in the relevant dimension.
    
    Returns
    -------
    state : :class:`qutip.Qobj`
      Qobj represent