In [32]:
import numpy as np
import matplotlib.pyplot as plt 
from matplotlib import animation
from matplotlib.animation import PillowWriter
import numba #finite diff algrothim for solving TDSE
from numba import jit
from scipy import linalg
from scipy.linalg import eigh_tridiagonal#matrix method for solving TDSE
#plt.style.use(['science', 'notebook', 'grid'])#some science plots

# bla

1. calculate hamiltonian
2. integrate
2. take partial trace


\begin{align}
a &= \int_{-\infty}^7 \\
b &= \int_{-\infty}^7 \sqrt{3} 
\left[\begin{array}{cc}
1 & 0 \\
0 & 5
\end{array}\right]
\end{align}

# bla

1. calculate hamiltonian
2. integrate
2. take partial trace


\begin{align}
a &= \int_{-\infty}^7 \\
b &= \int_{-\infty}^7 \sqrt{3} 
\left[\begin{array}{cc}
1 & 0 \\
0 & 5
\end{array}\right]
\end{align}

In [33]:
v=np.array([12,20,23,42,56])
print(v)

[12 20 23 42 56]


In [34]:
m = np.array([[11,23,45],
             [12,34,64],
             [34,65,75]])
print(m)

[[11 23 45]
 [12 34 64]
 [34 65 75]]


In [35]:
print(m.T)
print(v.T)

[[11 12 34]
 [23 34 65]
 [45 64 75]]
[12 20 23 42 56]


In [36]:
#hbar = 1 => 1 = Js => J = 1/s

H = np.array([[0,1],
            [1,4]])
time=np.linspace(0,1,100)
unitary = [linalg.expm(-(1j)*t*H) for t in time]

In [42]:
psiout = np.zeros(len(unitary))
v1 = np.ones(len(unitary))
#psiout = unitary*v1
psiout

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])